-- ============================================================
-- SEMILLA 009 - Catalogo de caracteristicas y matriz por rol
-- (docs/PERMISOS_Y_USUARIOS.md, seccion 3). Idempotente.
--
-- La matriz se siembra EXPLICITAMENTE: todas las combinaciones
-- rol x caracteristica existen como fila, ninguna es implicita.
--
-- Los valores por defecto REPRODUCEN el comportamiento anterior a
-- la migracion 014: si hoy un rol puede hacer algo, su
-- caracteristica nace habilitada; si no puede, nace deshabilitada.
-- AUDITOR: solo lectura y auditoria. SIN_ASIGNAR: nada.
--
-- Una celda que el administrador haya tocado (updated_by no nulo)
-- NO se pisa al volver a sembrar.
-- ============================================================

INSERT INTO feature_categories (code, name, description, sort_order) VALUES
  ('DOCUMENTS', 'Documentos', 'Acciones sobre documentos individuales', 1),
  ('EXPEDIENTES', 'Expedientes y correspondencia', 'Expedientes, series y radicación de correspondencia', 2),
  ('ARCHIVE', 'Archivo y retención', 'Tabla de Retención Documental y categorías', 3),
  ('LOANS', 'Préstamos', 'Préstamo y devolución de documentos', 4),
  ('TRASH', 'Papelera y eliminación', 'Papelera, purga y solicitudes de eliminación', 5),
  ('PEOPLE', 'Personas', 'Directorio de personas, eventos y periodos académicos', 6),
  ('SEARCH', 'Búsqueda', 'Motores de búsqueda del sistema', 7),
  ('AI', 'Inteligencia artificial', 'Análisis, reconocimiento óptico y asistente', 8),
  ('ANALYTICS', 'Análisis', 'Tableros y estadísticas', 9),
  ('AUDIT', 'Auditoría', 'Registros de auditoría y cadena de custodia', 10),
  ('ADMIN', 'Administración', 'Usuarios, roles, catálogos y configuración', 11),
  ('BILLING', 'Comercial', 'Clientes, cotizaciones, facturas, pagos y licencias', 12)
ON CONFLICT (code) DO UPDATE
   SET name = EXCLUDED.name, description = EXCLUDED.description, sort_order = EXCLUDED.sort_order;

INSERT INTO features (code, name, description, category_code, is_core, is_sensitive, sort_order) VALUES
  ('DOCUMENT_VIEW', 'Ver documentos', 'Consultar el listado y la ficha de los documentos de sus dependencias', 'DOCUMENTS', false, false, 10),
  ('DOCUMENT_DOWNLOAD', 'Descargar documentos', 'Obtener el archivo original o una de sus versiones', 'DOCUMENTS', false, false, 20),
  ('DOCUMENT_UPLOAD', 'Subir documentos', 'Crear documentos nuevos con archivo adjunto', 'DOCUMENTS', false, false, 30),
  ('DOCUMENT_EDIT', 'Editar documentos', 'Modificar título, tipo, categoría, resumen y vínculos del documento', 'DOCUMENTS', false, false, 40),
  ('DOCUMENT_FOLIO', 'Foliar documentos', 'Asignar el folio consecutivo del módulo', 'DOCUMENTS', false, false, 50),
  ('DOCUMENT_APPROVE', 'Aprobar documentos', 'Aprobar electrónicamente un documento (estado terminal)', 'DOCUMENTS', false, true, 60),
  ('DOCUMENT_LOCK', 'Bloquear y desbloquear', 'Aplicar y levantar el bloqueo administrativo', 'DOCUMENTS', false, true, 70),
  ('DOCUMENT_TRANSFER', 'Transferir documentos', 'Avanzar el documento en la secuencia archivística', 'DOCUMENTS', false, true, 80),
  ('DOCUMENT_VERSION_UPLOAD', 'Subir versiones', 'Añadir una versión nueva del archivo conservando la anterior', 'DOCUMENTS', false, false, 90),
  ('DOCUMENT_NOTE_ADD', 'Añadir notas', 'Escribir notas internas sobre el documento', 'DOCUMENTS', false, false, 100),
  ('DOCUMENT_METADATA_EDIT', 'Editar metadatos', 'Crear, actualizar y borrar metadatos del documento', 'DOCUMENTS', false, false, 110),
  ('DOCUMENT_TAG_EDIT', 'Editar etiquetas', 'Añadir y quitar etiquetas del documento', 'DOCUMENTS', false, false, 120),
  ('DOCUMENT_RELATION_MANAGE', 'Gestionar relaciones', 'Relacionar documentos entre sí y deshacer la relación', 'DOCUMENTS', false, false, 130),
  ('DOCUMENT_PERMISSION_MANAGE', 'Permisos por documento', 'Conceder o retirar permisos de un rol sobre un documento', 'DOCUMENTS', false, true, 140),
  ('DOCUMENT_TRASH', 'Enviar a la papelera', 'Mover documentos a la papelera con motivo', 'DOCUMENTS', false, true, 150),
  ('EXPEDIENTE_VIEW', 'Ver expedientes', 'Consultar expedientes y correspondencia', 'EXPEDIENTES', false, false, 160),
  ('EXPEDIENTE_CREATE', 'Crear expedientes', 'Abrir expedientes nuevos', 'EXPEDIENTES', false, false, 170),
  ('EXPEDIENTE_EDIT', 'Editar expedientes', 'Modificar datos y composición documental del expediente', 'EXPEDIENTES', false, false, 180),
  ('EXPEDIENTE_CLOSE', 'Cerrar expedientes', 'Cerrar un expediente en trámite', 'EXPEDIENTES', false, false, 190),
  ('EXPEDIENTE_REOPEN', 'Reabrir expedientes', 'Volver a abrir un expediente cerrado', 'EXPEDIENTES', false, true, 200),
  ('EXPEDIENTE_DELETE', 'Eliminar expedientes', 'Eliminar un expediente', 'EXPEDIENTES', false, true, 210),
  ('EXPEDIENTE_EXPORT', 'Exportar el FUID', 'Descargar el Formato Único de Inventario Documental', 'EXPEDIENTES', false, false, 220),
  ('CORRESPONDENCE_CREATE', 'Radicar correspondencia', 'Radicar correspondencia entrante, saliente o interna', 'EXPEDIENTES', false, false, 230),
  ('TRD_VIEW', 'Ver la TRD', 'Consultar la Tabla de Retención Documental', 'ARCHIVE', false, false, 240),
  ('TRD_EDIT', 'Editar la TRD', 'Crear, modificar y eliminar reglas de retención', 'ARCHIVE', false, true, 250),
  ('TRD_EXPORT', 'Exportar la TRD', 'Descargar la TRD en csv o xlsx', 'ARCHIVE', false, false, 260),
  ('CATEGORY_MANAGE', 'Gestionar categorías', 'Administrar el árbol de categorías documentales', 'ARCHIVE', false, false, 270),
  ('LOAN_VIEW', 'Ver préstamos', 'Consultar los préstamos documentales', 'LOANS', false, false, 280),
  ('LOAN_CREATE', 'Prestar documentos', 'Registrar el préstamo de un documento', 'LOANS', false, false, 290),
  ('LOAN_RETURN', 'Registrar devoluciones', 'Cerrar un préstamo con su devolución', 'LOANS', false, false, 300),
  ('TRASH_VIEW', 'Ver la papelera', 'Consultar los documentos en la papelera', 'TRASH', false, false, 310),
  ('TRASH_RESTORE', 'Restaurar de la papelera', 'Devolver un documento de la papelera al archivo', 'TRASH', false, false, 320),
  ('TRASH_PURGE', 'Purgar la papelera', 'Eliminar físicamente documentos y generar el acta', 'TRASH', false, true, 330),
  ('DELETION_REQUEST_CREATE', 'Solicitar eliminación', 'Pedir la eliminación de un documento con motivo', 'TRASH', false, false, 340),
  ('DELETION_REQUEST_REVIEW', 'Aprobar o rechazar eliminaciones', 'Resolver las solicitudes de eliminación', 'TRASH', false, true, 350),
  ('PEOPLE_VIEW', 'Ver personas', 'Consultar el directorio de personas', 'PEOPLE', false, false, 360),
  ('PEOPLE_MANAGE', 'Gestionar personas', 'Crear y editar personas y sus documentos obligatorios', 'PEOPLE', false, false, 370),
  ('PERSON_EVENT_ADD', 'Registrar eventos de persona', 'Añadir hitos a la hoja de vida de una persona', 'PEOPLE', false, false, 380),
  ('ACADEMIC_PERIOD_MANAGE', 'Gestionar periodos académicos', 'Crear y editar los periodos académicos', 'PEOPLE', false, false, 390),
  ('SEARCH_FULLTEXT', 'Búsqueda de texto completo', 'Buscar por contenido con el índice de texto completo', 'SEARCH', false, false, 400),
  ('SEARCH_ADVANCED', 'Búsqueda avanzada', 'Buscar con filtros combinados', 'SEARCH', false, false, 410),
  ('SEARCH_SEMANTIC', 'Búsqueda semántica', 'Buscar por significado con el motor de IA', 'SEARCH', false, false, 420),
  ('SEARCH_GLOBAL', 'Búsqueda global', 'Buscar a la vez en documentos, expedientes y personas', 'SEARCH', false, false, 430),
  ('AI_ANALYZE', 'Analizar con IA', 'Resumir y etiquetar un documento con el modelo', 'AI', false, false, 440),
  ('AI_CHAT', 'Conversar con el documento', 'Preguntar sobre el contenido con citas', 'AI', false, false, 450),
  ('AI_CLASSIFY', 'Clasificar con IA', 'Proponer tipo documental y categoría', 'AI', false, false, 460),
  ('AI_EXTRACT_METADATA', 'Extraer metadatos con IA', 'Proponer metadatos a partir del contenido', 'AI', false, false, 470),
  ('AI_OCR', 'Reconocimiento óptico', 'Transcribir documentos sin texto extraíble', 'AI', false, false, 480),
  ('AI_REPROCESS', 'Reprocesar en lote', 'Volver a analizar conjuntos de documentos', 'AI', false, true, 490),
  ('AI_USAGE_VIEW', 'Ver el consumo de IA', 'Consultar tokens, costo estimado y aciertos de caché', 'AI', false, false, 500),
  ('STATS_VIEW', 'Ver estadísticas', 'Consultar el tablero y las tendencias', 'ANALYTICS', false, false, 510),
  ('STATS_MODULE_VIEW', 'Ver estadísticas por dependencia', 'Consultar las cifras de un módulo concreto', 'ANALYTICS', false, false, 520),
  ('AUDIT_VIEW', 'Ver la auditoría', 'Consultar el registro de auditoría del sistema', 'AUDIT', false, true, 530),
  ('AUDIT_EXPORT', 'Exportar la auditoría', 'Descargar el registro de auditoría', 'AUDIT', false, true, 540),
  ('CUSTODY_VIEW', 'Ver la cadena de custodia', 'Consultar los eventos de custodia de un documento', 'AUDIT', false, false, 550),
  ('USER_VIEW', 'Ver usuarios', 'Consultar el listado y la ficha de los usuarios', 'ADMIN', false, false, 560),
  ('USER_MANAGE', 'Gestionar usuarios', 'Crear, editar, activar y desactivar usuarios', 'ADMIN', true, false, 570),
  ('USER_RESET_PASSWORD', 'Restablecer contraseñas', 'Generar una contraseña temporal a otro usuario', 'ADMIN', false, true, 580),
  ('USER_SESSION_REVOKE', 'Revocar sesiones', 'Cerrar las sesiones activas de un usuario', 'ADMIN', false, false, 590),
  ('ROLE_MANAGE', 'Gestionar roles', 'Crear y editar los roles del sistema', 'ADMIN', true, false, 600),
  ('ACCESS_MATRIX_MANAGE', 'Gestionar la matriz de dependencias', 'Editar el acceso de cada rol a cada dependencia', 'ADMIN', true, false, 610),
  ('FEATURE_MATRIX_MANAGE', 'Gestionar la matriz de características', 'Activar y desactivar características por rol', 'ADMIN', true, false, 620),
  ('CATALOG_MANAGE', 'Gestionar catálogos', 'Editar módulos, estados, disposiciones y demás catálogos', 'ADMIN', false, false, 630),
  ('SYSTEM_CONFIG_VIEW', 'Ver la configuración', 'Consultar la configuración del sistema', 'ADMIN', false, false, 640),
  ('SYSTEM_CONFIG_EDIT', 'Editar la configuración', 'Modificar la configuración, el almacenamiento y el correo', 'ADMIN', true, false, 650),
  ('JOB_RUN', 'Ejecutar trabajos', 'Lanzar manualmente los trabajos programados', 'ADMIN', false, false, 660),
  ('HELP_EDIT', 'Editar la ayuda', 'Crear y modificar los artículos de ayuda', 'ADMIN', false, false, 670),
  ('BILLING_VIEW', 'Ver el panel comercial', 'Consultar clientes, cotizaciones, facturas y pagos', 'BILLING', false, false, 680),
  ('CLIENT_MANAGE', 'Gestionar clientes', 'Crear y editar los clientes de EduArchive', 'BILLING', false, false, 690),
  ('QUOTE_MANAGE', 'Gestionar cotizaciones', 'Crear, enviar, decidir y convertir cotizaciones', 'BILLING', false, false, 700),
  ('INVOICE_MANAGE', 'Gestionar facturas', 'Crear, emitir y anular facturas', 'BILLING', false, false, 710),
  ('PAYMENT_MANAGE', 'Gestionar pagos', 'Registrar y revertir pagos de facturas', 'BILLING', false, false, 720),
  ('LICENSE_MANAGE', 'Gestionar licencias y planes', 'Contratar, renovar y editar licencias y planes', 'BILLING', false, false, 730)
ON CONFLICT (code) DO UPDATE
   SET name = EXCLUDED.name, description = EXCLUDED.description,
       category_code = EXCLUDED.category_code, is_core = EXCLUDED.is_core,
       is_sensitive = EXCLUDED.is_sensitive, sort_order = EXCLUDED.sort_order;

-- Valores por defecto (dato, no constante del codigo): los usa la semilla
-- y los restaura POST /features/matrix/reset.
INSERT INTO role_feature_defaults (role_code, feature_code, enabled) VALUES
  ('ADMIN', 'DOCUMENT_VIEW', true),
  ('ADMIN', 'DOCUMENT_DOWNLOAD', true),
  ('ADMIN', 'DOCUMENT_UPLOAD', true),
  ('ADMIN', 'DOCUMENT_EDIT', true),
  ('ADMIN', 'DOCUMENT_FOLIO', true),
  ('ADMIN', 'DOCUMENT_APPROVE', true),
  ('ADMIN', 'DOCUMENT_LOCK', true),
  ('ADMIN', 'DOCUMENT_TRANSFER', true),
  ('ADMIN', 'DOCUMENT_VERSION_UPLOAD', true),
  ('ADMIN', 'DOCUMENT_NOTE_ADD', true),
  ('ADMIN', 'DOCUMENT_METADATA_EDIT', true),
  ('ADMIN', 'DOCUMENT_TAG_EDIT', true),
  ('ADMIN', 'DOCUMENT_RELATION_MANAGE', true),
  ('ADMIN', 'DOCUMENT_PERMISSION_MANAGE', true),
  ('ADMIN', 'DOCUMENT_TRASH', true),
  ('ADMIN', 'EXPEDIENTE_VIEW', true),
  ('ADMIN', 'EXPEDIENTE_CREATE', true),
  ('ADMIN', 'EXPEDIENTE_EDIT', true),
  ('ADMIN', 'EXPEDIENTE_CLOSE', true),
  ('ADMIN', 'EXPEDIENTE_REOPEN', true),
  ('ADMIN', 'EXPEDIENTE_DELETE', true),
  ('ADMIN', 'EXPEDIENTE_EXPORT', true),
  ('ADMIN', 'CORRESPONDENCE_CREATE', true),
  ('ADMIN', 'TRD_VIEW', true),
  ('ADMIN', 'TRD_EDIT', true),
  ('ADMIN', 'TRD_EXPORT', true),
  ('ADMIN', 'CATEGORY_MANAGE', true),
  ('ADMIN', 'LOAN_VIEW', true),
  ('ADMIN', 'LOAN_CREATE', true),
  ('ADMIN', 'LOAN_RETURN', true),
  ('ADMIN', 'TRASH_VIEW', true),
  ('ADMIN', 'TRASH_RESTORE', true),
  ('ADMIN', 'TRASH_PURGE', true),
  ('ADMIN', 'DELETION_REQUEST_CREATE', true),
  ('ADMIN', 'DELETION_REQUEST_REVIEW', true),
  ('ADMIN', 'PEOPLE_VIEW', true),
  ('ADMIN', 'PEOPLE_MANAGE', true),
  ('ADMIN', 'PERSON_EVENT_ADD', true),
  ('ADMIN', 'ACADEMIC_PERIOD_MANAGE', true),
  ('ADMIN', 'SEARCH_FULLTEXT', true),
  ('ADMIN', 'SEARCH_ADVANCED', true),
  ('ADMIN', 'SEARCH_SEMANTIC', true),
  ('ADMIN', 'SEARCH_GLOBAL', true),
  ('ADMIN', 'AI_ANALYZE', true),
  ('ADMIN', 'AI_CHAT', true),
  ('ADMIN', 'AI_CLASSIFY', true),
  ('ADMIN', 'AI_EXTRACT_METADATA', true),
  ('ADMIN', 'AI_OCR', true),
  ('ADMIN', 'AI_REPROCESS', true),
  ('ADMIN', 'AI_USAGE_VIEW', true),
  ('ADMIN', 'STATS_VIEW', true),
  ('ADMIN', 'STATS_MODULE_VIEW', true),
  ('ADMIN', 'AUDIT_VIEW', true),
  ('ADMIN', 'AUDIT_EXPORT', true),
  ('ADMIN', 'CUSTODY_VIEW', true),
  ('ADMIN', 'USER_VIEW', true),
  ('ADMIN', 'USER_MANAGE', true),
  ('ADMIN', 'USER_RESET_PASSWORD', true),
  ('ADMIN', 'USER_SESSION_REVOKE', true),
  ('ADMIN', 'ROLE_MANAGE', true),
  ('ADMIN', 'ACCESS_MATRIX_MANAGE', true),
  ('ADMIN', 'FEATURE_MATRIX_MANAGE', true),
  ('ADMIN', 'CATALOG_MANAGE', true),
  ('ADMIN', 'SYSTEM_CONFIG_VIEW', true),
  ('ADMIN', 'SYSTEM_CONFIG_EDIT', true),
  ('ADMIN', 'JOB_RUN', true),
  ('ADMIN', 'HELP_EDIT', true),
  ('ADMIN', 'BILLING_VIEW', true),
  ('ADMIN', 'CLIENT_MANAGE', true),
  ('ADMIN', 'QUOTE_MANAGE', true),
  ('ADMIN', 'INVOICE_MANAGE', true),
  ('ADMIN', 'PAYMENT_MANAGE', true),
  ('ADMIN', 'LICENSE_MANAGE', true),
  ('RECTOR', 'DOCUMENT_VIEW', true),
  ('RECTOR', 'DOCUMENT_DOWNLOAD', true),
  ('RECTOR', 'DOCUMENT_UPLOAD', true),
  ('RECTOR', 'DOCUMENT_EDIT', true),
  ('RECTOR', 'DOCUMENT_FOLIO', true),
  ('RECTOR', 'DOCUMENT_APPROVE', true),
  ('RECTOR', 'DOCUMENT_LOCK', true),
  ('RECTOR', 'DOCUMENT_TRANSFER', true),
  ('RECTOR', 'DOCUMENT_VERSION_UPLOAD', true),
  ('RECTOR', 'DOCUMENT_NOTE_ADD', true),
  ('RECTOR', 'DOCUMENT_METADATA_EDIT', true),
  ('RECTOR', 'DOCUMENT_TAG_EDIT', true),
  ('RECTOR', 'DOCUMENT_RELATION_MANAGE', true),
  ('RECTOR', 'DOCUMENT_PERMISSION_MANAGE', true),
  ('RECTOR', 'DOCUMENT_TRASH', true),
  ('RECTOR', 'EXPEDIENTE_VIEW', true),
  ('RECTOR', 'EXPEDIENTE_CREATE', true),
  ('RECTOR', 'EXPEDIENTE_EDIT', true),
  ('RECTOR', 'EXPEDIENTE_CLOSE', true),
  ('RECTOR', 'EXPEDIENTE_REOPEN', true),
  ('RECTOR', 'EXPEDIENTE_DELETE', true),
  ('RECTOR', 'EXPEDIENTE_EXPORT', true),
  ('RECTOR', 'CORRESPONDENCE_CREATE', true),
  ('RECTOR', 'TRD_VIEW', true),
  ('RECTOR', 'TRD_EDIT', true),
  ('RECTOR', 'TRD_EXPORT', true),
  ('RECTOR', 'CATEGORY_MANAGE', true),
  ('RECTOR', 'LOAN_VIEW', true),
  ('RECTOR', 'LOAN_CREATE', true),
  ('RECTOR', 'LOAN_RETURN', true),
  ('RECTOR', 'TRASH_VIEW', true),
  ('RECTOR', 'TRASH_RESTORE', true),
  ('RECTOR', 'TRASH_PURGE', true),
  ('RECTOR', 'DELETION_REQUEST_CREATE', true),
  ('RECTOR', 'DELETION_REQUEST_REVIEW', true),
  ('RECTOR', 'PEOPLE_VIEW', true),
  ('RECTOR', 'PEOPLE_MANAGE', true),
  ('RECTOR', 'PERSON_EVENT_ADD', true),
  ('RECTOR', 'ACADEMIC_PERIOD_MANAGE', true),
  ('RECTOR', 'SEARCH_FULLTEXT', true),
  ('RECTOR', 'SEARCH_ADVANCED', true),
  ('RECTOR', 'SEARCH_SEMANTIC', true),
  ('RECTOR', 'SEARCH_GLOBAL', true),
  ('RECTOR', 'AI_ANALYZE', true),
  ('RECTOR', 'AI_CHAT', true),
  ('RECTOR', 'AI_CLASSIFY', true),
  ('RECTOR', 'AI_EXTRACT_METADATA', true),
  ('RECTOR', 'AI_OCR', true),
  ('RECTOR', 'AI_REPROCESS', true),
  ('RECTOR', 'AI_USAGE_VIEW', true),
  ('RECTOR', 'STATS_VIEW', true),
  ('RECTOR', 'STATS_MODULE_VIEW', true),
  ('RECTOR', 'AUDIT_VIEW', true),
  ('RECTOR', 'AUDIT_EXPORT', true),
  ('RECTOR', 'CUSTODY_VIEW', true),
  ('RECTOR', 'USER_VIEW', true),
  ('RECTOR', 'USER_MANAGE', true),
  ('RECTOR', 'USER_RESET_PASSWORD', true),
  ('RECTOR', 'USER_SESSION_REVOKE', true),
  ('RECTOR', 'ROLE_MANAGE', true),
  ('RECTOR', 'ACCESS_MATRIX_MANAGE', true),
  ('RECTOR', 'FEATURE_MATRIX_MANAGE', true),
  ('RECTOR', 'CATALOG_MANAGE', true),
  ('RECTOR', 'SYSTEM_CONFIG_VIEW', true),
  ('RECTOR', 'SYSTEM_CONFIG_EDIT', true),
  ('RECTOR', 'JOB_RUN', true),
  ('RECTOR', 'HELP_EDIT', true),
  ('RECTOR', 'BILLING_VIEW', true),
  ('RECTOR', 'CLIENT_MANAGE', true),
  ('RECTOR', 'QUOTE_MANAGE', true),
  ('RECTOR', 'INVOICE_MANAGE', true),
  ('RECTOR', 'PAYMENT_MANAGE', true),
  ('RECTOR', 'LICENSE_MANAGE', true),
  ('ARCHIVISTA', 'DOCUMENT_VIEW', true),
  ('ARCHIVISTA', 'DOCUMENT_DOWNLOAD', true),
  ('ARCHIVISTA', 'DOCUMENT_UPLOAD', true),
  ('ARCHIVISTA', 'DOCUMENT_EDIT', true),
  ('ARCHIVISTA', 'DOCUMENT_FOLIO', true),
  ('ARCHIVISTA', 'DOCUMENT_APPROVE', true),
  ('ARCHIVISTA', 'DOCUMENT_LOCK', true),
  ('ARCHIVISTA', 'DOCUMENT_TRANSFER', true),
  ('ARCHIVISTA', 'DOCUMENT_VERSION_UPLOAD', true),
  ('ARCHIVISTA', 'DOCUMENT_NOTE_ADD', true),
  ('ARCHIVISTA', 'DOCUMENT_METADATA_EDIT', true),
  ('ARCHIVISTA', 'DOCUMENT_TAG_EDIT', true),
  ('ARCHIVISTA', 'DOCUMENT_RELATION_MANAGE', true),
  ('ARCHIVISTA', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('ARCHIVISTA', 'DOCUMENT_TRASH', true),
  ('ARCHIVISTA', 'EXPEDIENTE_VIEW', true),
  ('ARCHIVISTA', 'EXPEDIENTE_CREATE', true),
  ('ARCHIVISTA', 'EXPEDIENTE_EDIT', true),
  ('ARCHIVISTA', 'EXPEDIENTE_CLOSE', true),
  ('ARCHIVISTA', 'EXPEDIENTE_REOPEN', true),
  ('ARCHIVISTA', 'EXPEDIENTE_DELETE', true),
  ('ARCHIVISTA', 'EXPEDIENTE_EXPORT', true),
  ('ARCHIVISTA', 'CORRESPONDENCE_CREATE', true),
  ('ARCHIVISTA', 'TRD_VIEW', true),
  ('ARCHIVISTA', 'TRD_EDIT', true),
  ('ARCHIVISTA', 'TRD_EXPORT', true),
  ('ARCHIVISTA', 'CATEGORY_MANAGE', false),
  ('ARCHIVISTA', 'LOAN_VIEW', true),
  ('ARCHIVISTA', 'LOAN_CREATE', true),
  ('ARCHIVISTA', 'LOAN_RETURN', true),
  ('ARCHIVISTA', 'TRASH_VIEW', true),
  ('ARCHIVISTA', 'TRASH_RESTORE', true),
  ('ARCHIVISTA', 'TRASH_PURGE', false),
  ('ARCHIVISTA', 'DELETION_REQUEST_CREATE', true),
  ('ARCHIVISTA', 'DELETION_REQUEST_REVIEW', false),
  ('ARCHIVISTA', 'PEOPLE_VIEW', true),
  ('ARCHIVISTA', 'PEOPLE_MANAGE', true),
  ('ARCHIVISTA', 'PERSON_EVENT_ADD', true),
  ('ARCHIVISTA', 'ACADEMIC_PERIOD_MANAGE', false),
  ('ARCHIVISTA', 'SEARCH_FULLTEXT', true),
  ('ARCHIVISTA', 'SEARCH_ADVANCED', true),
  ('ARCHIVISTA', 'SEARCH_SEMANTIC', true),
  ('ARCHIVISTA', 'SEARCH_GLOBAL', true),
  ('ARCHIVISTA', 'AI_ANALYZE', true),
  ('ARCHIVISTA', 'AI_CHAT', true),
  ('ARCHIVISTA', 'AI_CLASSIFY', true),
  ('ARCHIVISTA', 'AI_EXTRACT_METADATA', true),
  ('ARCHIVISTA', 'AI_OCR', true),
  ('ARCHIVISTA', 'AI_REPROCESS', false),
  ('ARCHIVISTA', 'AI_USAGE_VIEW', false),
  ('ARCHIVISTA', 'STATS_VIEW', true),
  ('ARCHIVISTA', 'STATS_MODULE_VIEW', true),
  ('ARCHIVISTA', 'AUDIT_VIEW', false),
  ('ARCHIVISTA', 'AUDIT_EXPORT', false),
  ('ARCHIVISTA', 'CUSTODY_VIEW', true),
  ('ARCHIVISTA', 'USER_VIEW', false),
  ('ARCHIVISTA', 'USER_MANAGE', false),
  ('ARCHIVISTA', 'USER_RESET_PASSWORD', false),
  ('ARCHIVISTA', 'USER_SESSION_REVOKE', false),
  ('ARCHIVISTA', 'ROLE_MANAGE', false),
  ('ARCHIVISTA', 'ACCESS_MATRIX_MANAGE', false),
  ('ARCHIVISTA', 'FEATURE_MATRIX_MANAGE', false),
  ('ARCHIVISTA', 'CATALOG_MANAGE', false),
  ('ARCHIVISTA', 'SYSTEM_CONFIG_VIEW', false),
  ('ARCHIVISTA', 'SYSTEM_CONFIG_EDIT', false),
  ('ARCHIVISTA', 'JOB_RUN', false),
  ('ARCHIVISTA', 'HELP_EDIT', false),
  ('ARCHIVISTA', 'BILLING_VIEW', false),
  ('ARCHIVISTA', 'CLIENT_MANAGE', false),
  ('ARCHIVISTA', 'QUOTE_MANAGE', false),
  ('ARCHIVISTA', 'INVOICE_MANAGE', false),
  ('ARCHIVISTA', 'PAYMENT_MANAGE', false),
  ('ARCHIVISTA', 'LICENSE_MANAGE', false),
  ('AUDITOR', 'DOCUMENT_VIEW', true),
  ('AUDITOR', 'DOCUMENT_DOWNLOAD', true),
  ('AUDITOR', 'DOCUMENT_UPLOAD', false),
  ('AUDITOR', 'DOCUMENT_EDIT', false),
  ('AUDITOR', 'DOCUMENT_FOLIO', false),
  ('AUDITOR', 'DOCUMENT_APPROVE', false),
  ('AUDITOR', 'DOCUMENT_LOCK', false),
  ('AUDITOR', 'DOCUMENT_TRANSFER', false),
  ('AUDITOR', 'DOCUMENT_VERSION_UPLOAD', false),
  ('AUDITOR', 'DOCUMENT_NOTE_ADD', false),
  ('AUDITOR', 'DOCUMENT_METADATA_EDIT', false),
  ('AUDITOR', 'DOCUMENT_TAG_EDIT', false),
  ('AUDITOR', 'DOCUMENT_RELATION_MANAGE', false),
  ('AUDITOR', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('AUDITOR', 'DOCUMENT_TRASH', false),
  ('AUDITOR', 'EXPEDIENTE_VIEW', true),
  ('AUDITOR', 'EXPEDIENTE_CREATE', false),
  ('AUDITOR', 'EXPEDIENTE_EDIT', false),
  ('AUDITOR', 'EXPEDIENTE_CLOSE', false),
  ('AUDITOR', 'EXPEDIENTE_REOPEN', false),
  ('AUDITOR', 'EXPEDIENTE_DELETE', false),
  ('AUDITOR', 'EXPEDIENTE_EXPORT', true),
  ('AUDITOR', 'CORRESPONDENCE_CREATE', false),
  ('AUDITOR', 'TRD_VIEW', true),
  ('AUDITOR', 'TRD_EDIT', false),
  ('AUDITOR', 'TRD_EXPORT', true),
  ('AUDITOR', 'CATEGORY_MANAGE', false),
  ('AUDITOR', 'LOAN_VIEW', true),
  ('AUDITOR', 'LOAN_CREATE', false),
  ('AUDITOR', 'LOAN_RETURN', false),
  ('AUDITOR', 'TRASH_VIEW', true),
  ('AUDITOR', 'TRASH_RESTORE', false),
  ('AUDITOR', 'TRASH_PURGE', false),
  ('AUDITOR', 'DELETION_REQUEST_CREATE', false),
  ('AUDITOR', 'DELETION_REQUEST_REVIEW', false),
  ('AUDITOR', 'PEOPLE_VIEW', true),
  ('AUDITOR', 'PEOPLE_MANAGE', false),
  ('AUDITOR', 'PERSON_EVENT_ADD', false),
  ('AUDITOR', 'ACADEMIC_PERIOD_MANAGE', false),
  ('AUDITOR', 'SEARCH_FULLTEXT', true),
  ('AUDITOR', 'SEARCH_ADVANCED', true),
  ('AUDITOR', 'SEARCH_SEMANTIC', true),
  ('AUDITOR', 'SEARCH_GLOBAL', true),
  ('AUDITOR', 'AI_ANALYZE', false),
  ('AUDITOR', 'AI_CHAT', true),
  ('AUDITOR', 'AI_CLASSIFY', true),
  ('AUDITOR', 'AI_EXTRACT_METADATA', true),
  ('AUDITOR', 'AI_OCR', false),
  ('AUDITOR', 'AI_REPROCESS', false),
  ('AUDITOR', 'AI_USAGE_VIEW', false),
  ('AUDITOR', 'STATS_VIEW', true),
  ('AUDITOR', 'STATS_MODULE_VIEW', true),
  ('AUDITOR', 'AUDIT_VIEW', true),
  ('AUDITOR', 'AUDIT_EXPORT', true),
  ('AUDITOR', 'CUSTODY_VIEW', true),
  ('AUDITOR', 'USER_VIEW', false),
  ('AUDITOR', 'USER_MANAGE', false),
  ('AUDITOR', 'USER_RESET_PASSWORD', false),
  ('AUDITOR', 'USER_SESSION_REVOKE', false),
  ('AUDITOR', 'ROLE_MANAGE', false),
  ('AUDITOR', 'ACCESS_MATRIX_MANAGE', false),
  ('AUDITOR', 'FEATURE_MATRIX_MANAGE', false),
  ('AUDITOR', 'CATALOG_MANAGE', false),
  ('AUDITOR', 'SYSTEM_CONFIG_VIEW', false),
  ('AUDITOR', 'SYSTEM_CONFIG_EDIT', false),
  ('AUDITOR', 'JOB_RUN', false),
  ('AUDITOR', 'HELP_EDIT', false),
  ('AUDITOR', 'BILLING_VIEW', false),
  ('AUDITOR', 'CLIENT_MANAGE', false),
  ('AUDITOR', 'QUOTE_MANAGE', false),
  ('AUDITOR', 'INVOICE_MANAGE', false),
  ('AUDITOR', 'PAYMENT_MANAGE', false),
  ('AUDITOR', 'LICENSE_MANAGE', false),
  ('DOCENTE', 'DOCUMENT_VIEW', true),
  ('DOCENTE', 'DOCUMENT_DOWNLOAD', true),
  ('DOCENTE', 'DOCUMENT_UPLOAD', true),
  ('DOCENTE', 'DOCUMENT_EDIT', true),
  ('DOCENTE', 'DOCUMENT_FOLIO', true),
  ('DOCENTE', 'DOCUMENT_APPROVE', true),
  ('DOCENTE', 'DOCUMENT_LOCK', true),
  ('DOCENTE', 'DOCUMENT_TRANSFER', true),
  ('DOCENTE', 'DOCUMENT_VERSION_UPLOAD', true),
  ('DOCENTE', 'DOCUMENT_NOTE_ADD', true),
  ('DOCENTE', 'DOCUMENT_METADATA_EDIT', true),
  ('DOCENTE', 'DOCUMENT_TAG_EDIT', true),
  ('DOCENTE', 'DOCUMENT_RELATION_MANAGE', true),
  ('DOCENTE', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('DOCENTE', 'DOCUMENT_TRASH', true),
  ('DOCENTE', 'EXPEDIENTE_VIEW', true),
  ('DOCENTE', 'EXPEDIENTE_CREATE', true),
  ('DOCENTE', 'EXPEDIENTE_EDIT', true),
  ('DOCENTE', 'EXPEDIENTE_CLOSE', true),
  ('DOCENTE', 'EXPEDIENTE_REOPEN', true),
  ('DOCENTE', 'EXPEDIENTE_DELETE', true),
  ('DOCENTE', 'EXPEDIENTE_EXPORT', true),
  ('DOCENTE', 'CORRESPONDENCE_CREATE', true),
  ('DOCENTE', 'TRD_VIEW', true),
  ('DOCENTE', 'TRD_EDIT', true),
  ('DOCENTE', 'TRD_EXPORT', true),
  ('DOCENTE', 'CATEGORY_MANAGE', false),
  ('DOCENTE', 'LOAN_VIEW', true),
  ('DOCENTE', 'LOAN_CREATE', true),
  ('DOCENTE', 'LOAN_RETURN', true),
  ('DOCENTE', 'TRASH_VIEW', true),
  ('DOCENTE', 'TRASH_RESTORE', true),
  ('DOCENTE', 'TRASH_PURGE', false),
  ('DOCENTE', 'DELETION_REQUEST_CREATE', true),
  ('DOCENTE', 'DELETION_REQUEST_REVIEW', false),
  ('DOCENTE', 'PEOPLE_VIEW', true),
  ('DOCENTE', 'PEOPLE_MANAGE', true),
  ('DOCENTE', 'PERSON_EVENT_ADD', true),
  ('DOCENTE', 'ACADEMIC_PERIOD_MANAGE', false),
  ('DOCENTE', 'SEARCH_FULLTEXT', true),
  ('DOCENTE', 'SEARCH_ADVANCED', true),
  ('DOCENTE', 'SEARCH_SEMANTIC', true),
  ('DOCENTE', 'SEARCH_GLOBAL', true),
  ('DOCENTE', 'AI_ANALYZE', true),
  ('DOCENTE', 'AI_CHAT', true),
  ('DOCENTE', 'AI_CLASSIFY', true),
  ('DOCENTE', 'AI_EXTRACT_METADATA', true),
  ('DOCENTE', 'AI_OCR', true),
  ('DOCENTE', 'AI_REPROCESS', false),
  ('DOCENTE', 'AI_USAGE_VIEW', false),
  ('DOCENTE', 'STATS_VIEW', true),
  ('DOCENTE', 'STATS_MODULE_VIEW', true),
  ('DOCENTE', 'AUDIT_VIEW', false),
  ('DOCENTE', 'AUDIT_EXPORT', false),
  ('DOCENTE', 'CUSTODY_VIEW', false),
  ('DOCENTE', 'USER_VIEW', false),
  ('DOCENTE', 'USER_MANAGE', false),
  ('DOCENTE', 'USER_RESET_PASSWORD', false),
  ('DOCENTE', 'USER_SESSION_REVOKE', false),
  ('DOCENTE', 'ROLE_MANAGE', false),
  ('DOCENTE', 'ACCESS_MATRIX_MANAGE', false),
  ('DOCENTE', 'FEATURE_MATRIX_MANAGE', false),
  ('DOCENTE', 'CATALOG_MANAGE', false),
  ('DOCENTE', 'SYSTEM_CONFIG_VIEW', false),
  ('DOCENTE', 'SYSTEM_CONFIG_EDIT', false),
  ('DOCENTE', 'JOB_RUN', false),
  ('DOCENTE', 'HELP_EDIT', false),
  ('DOCENTE', 'BILLING_VIEW', false),
  ('DOCENTE', 'CLIENT_MANAGE', false),
  ('DOCENTE', 'QUOTE_MANAGE', false),
  ('DOCENTE', 'INVOICE_MANAGE', false),
  ('DOCENTE', 'PAYMENT_MANAGE', false),
  ('DOCENTE', 'LICENSE_MANAGE', false),
  ('ADMINISTRATIVO', 'DOCUMENT_VIEW', true),
  ('ADMINISTRATIVO', 'DOCUMENT_DOWNLOAD', true),
  ('ADMINISTRATIVO', 'DOCUMENT_UPLOAD', true),
  ('ADMINISTRATIVO', 'DOCUMENT_EDIT', true),
  ('ADMINISTRATIVO', 'DOCUMENT_FOLIO', true),
  ('ADMINISTRATIVO', 'DOCUMENT_APPROVE', true),
  ('ADMINISTRATIVO', 'DOCUMENT_LOCK', true),
  ('ADMINISTRATIVO', 'DOCUMENT_TRANSFER', true),
  ('ADMINISTRATIVO', 'DOCUMENT_VERSION_UPLOAD', true),
  ('ADMINISTRATIVO', 'DOCUMENT_NOTE_ADD', true),
  ('ADMINISTRATIVO', 'DOCUMENT_METADATA_EDIT', true),
  ('ADMINISTRATIVO', 'DOCUMENT_TAG_EDIT', true),
  ('ADMINISTRATIVO', 'DOCUMENT_RELATION_MANAGE', true),
  ('ADMINISTRATIVO', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('ADMINISTRATIVO', 'DOCUMENT_TRASH', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_VIEW', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_CREATE', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_EDIT', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_CLOSE', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_REOPEN', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_DELETE', true),
  ('ADMINISTRATIVO', 'EXPEDIENTE_EXPORT', true),
  ('ADMINISTRATIVO', 'CORRESPONDENCE_CREATE', true),
  ('ADMINISTRATIVO', 'TRD_VIEW', true),
  ('ADMINISTRATIVO', 'TRD_EDIT', true),
  ('ADMINISTRATIVO', 'TRD_EXPORT', true),
  ('ADMINISTRATIVO', 'CATEGORY_MANAGE', false),
  ('ADMINISTRATIVO', 'LOAN_VIEW', true),
  ('ADMINISTRATIVO', 'LOAN_CREATE', true),
  ('ADMINISTRATIVO', 'LOAN_RETURN', true),
  ('ADMINISTRATIVO', 'TRASH_VIEW', true),
  ('ADMINISTRATIVO', 'TRASH_RESTORE', true),
  ('ADMINISTRATIVO', 'TRASH_PURGE', false),
  ('ADMINISTRATIVO', 'DELETION_REQUEST_CREATE', true),
  ('ADMINISTRATIVO', 'DELETION_REQUEST_REVIEW', false),
  ('ADMINISTRATIVO', 'PEOPLE_VIEW', true),
  ('ADMINISTRATIVO', 'PEOPLE_MANAGE', true),
  ('ADMINISTRATIVO', 'PERSON_EVENT_ADD', true),
  ('ADMINISTRATIVO', 'ACADEMIC_PERIOD_MANAGE', false),
  ('ADMINISTRATIVO', 'SEARCH_FULLTEXT', true),
  ('ADMINISTRATIVO', 'SEARCH_ADVANCED', true),
  ('ADMINISTRATIVO', 'SEARCH_SEMANTIC', true),
  ('ADMINISTRATIVO', 'SEARCH_GLOBAL', true),
  ('ADMINISTRATIVO', 'AI_ANALYZE', true),
  ('ADMINISTRATIVO', 'AI_CHAT', true),
  ('ADMINISTRATIVO', 'AI_CLASSIFY', true),
  ('ADMINISTRATIVO', 'AI_EXTRACT_METADATA', true),
  ('ADMINISTRATIVO', 'AI_OCR', true),
  ('ADMINISTRATIVO', 'AI_REPROCESS', false),
  ('ADMINISTRATIVO', 'AI_USAGE_VIEW', false),
  ('ADMINISTRATIVO', 'STATS_VIEW', true),
  ('ADMINISTRATIVO', 'STATS_MODULE_VIEW', true),
  ('ADMINISTRATIVO', 'AUDIT_VIEW', false),
  ('ADMINISTRATIVO', 'AUDIT_EXPORT', false),
  ('ADMINISTRATIVO', 'CUSTODY_VIEW', false),
  ('ADMINISTRATIVO', 'USER_VIEW', false),
  ('ADMINISTRATIVO', 'USER_MANAGE', false),
  ('ADMINISTRATIVO', 'USER_RESET_PASSWORD', false),
  ('ADMINISTRATIVO', 'USER_SESSION_REVOKE', false),
  ('ADMINISTRATIVO', 'ROLE_MANAGE', false),
  ('ADMINISTRATIVO', 'ACCESS_MATRIX_MANAGE', false),
  ('ADMINISTRATIVO', 'FEATURE_MATRIX_MANAGE', false),
  ('ADMINISTRATIVO', 'CATALOG_MANAGE', false),
  ('ADMINISTRATIVO', 'SYSTEM_CONFIG_VIEW', false),
  ('ADMINISTRATIVO', 'SYSTEM_CONFIG_EDIT', false),
  ('ADMINISTRATIVO', 'JOB_RUN', false),
  ('ADMINISTRATIVO', 'HELP_EDIT', false),
  ('ADMINISTRATIVO', 'BILLING_VIEW', false),
  ('ADMINISTRATIVO', 'CLIENT_MANAGE', false),
  ('ADMINISTRATIVO', 'QUOTE_MANAGE', false),
  ('ADMINISTRATIVO', 'INVOICE_MANAGE', false),
  ('ADMINISTRATIVO', 'PAYMENT_MANAGE', false),
  ('ADMINISTRATIVO', 'LICENSE_MANAGE', false),
  ('RRHH', 'DOCUMENT_VIEW', true),
  ('RRHH', 'DOCUMENT_DOWNLOAD', true),
  ('RRHH', 'DOCUMENT_UPLOAD', true),
  ('RRHH', 'DOCUMENT_EDIT', true),
  ('RRHH', 'DOCUMENT_FOLIO', true),
  ('RRHH', 'DOCUMENT_APPROVE', true),
  ('RRHH', 'DOCUMENT_LOCK', true),
  ('RRHH', 'DOCUMENT_TRANSFER', true),
  ('RRHH', 'DOCUMENT_VERSION_UPLOAD', true),
  ('RRHH', 'DOCUMENT_NOTE_ADD', true),
  ('RRHH', 'DOCUMENT_METADATA_EDIT', true),
  ('RRHH', 'DOCUMENT_TAG_EDIT', true),
  ('RRHH', 'DOCUMENT_RELATION_MANAGE', true),
  ('RRHH', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('RRHH', 'DOCUMENT_TRASH', true),
  ('RRHH', 'EXPEDIENTE_VIEW', true),
  ('RRHH', 'EXPEDIENTE_CREATE', true),
  ('RRHH', 'EXPEDIENTE_EDIT', true),
  ('RRHH', 'EXPEDIENTE_CLOSE', true),
  ('RRHH', 'EXPEDIENTE_REOPEN', true),
  ('RRHH', 'EXPEDIENTE_DELETE', true),
  ('RRHH', 'EXPEDIENTE_EXPORT', true),
  ('RRHH', 'CORRESPONDENCE_CREATE', true),
  ('RRHH', 'TRD_VIEW', true),
  ('RRHH', 'TRD_EDIT', true),
  ('RRHH', 'TRD_EXPORT', true),
  ('RRHH', 'CATEGORY_MANAGE', false),
  ('RRHH', 'LOAN_VIEW', true),
  ('RRHH', 'LOAN_CREATE', true),
  ('RRHH', 'LOAN_RETURN', true),
  ('RRHH', 'TRASH_VIEW', true),
  ('RRHH', 'TRASH_RESTORE', true),
  ('RRHH', 'TRASH_PURGE', false),
  ('RRHH', 'DELETION_REQUEST_CREATE', true),
  ('RRHH', 'DELETION_REQUEST_REVIEW', false),
  ('RRHH', 'PEOPLE_VIEW', true),
  ('RRHH', 'PEOPLE_MANAGE', true),
  ('RRHH', 'PERSON_EVENT_ADD', true),
  ('RRHH', 'ACADEMIC_PERIOD_MANAGE', false),
  ('RRHH', 'SEARCH_FULLTEXT', true),
  ('RRHH', 'SEARCH_ADVANCED', true),
  ('RRHH', 'SEARCH_SEMANTIC', true),
  ('RRHH', 'SEARCH_GLOBAL', true),
  ('RRHH', 'AI_ANALYZE', true),
  ('RRHH', 'AI_CHAT', true),
  ('RRHH', 'AI_CLASSIFY', true),
  ('RRHH', 'AI_EXTRACT_METADATA', true),
  ('RRHH', 'AI_OCR', true),
  ('RRHH', 'AI_REPROCESS', false),
  ('RRHH', 'AI_USAGE_VIEW', false),
  ('RRHH', 'STATS_VIEW', true),
  ('RRHH', 'STATS_MODULE_VIEW', true),
  ('RRHH', 'AUDIT_VIEW', false),
  ('RRHH', 'AUDIT_EXPORT', false),
  ('RRHH', 'CUSTODY_VIEW', false),
  ('RRHH', 'USER_VIEW', false),
  ('RRHH', 'USER_MANAGE', false),
  ('RRHH', 'USER_RESET_PASSWORD', false),
  ('RRHH', 'USER_SESSION_REVOKE', false),
  ('RRHH', 'ROLE_MANAGE', false),
  ('RRHH', 'ACCESS_MATRIX_MANAGE', false),
  ('RRHH', 'FEATURE_MATRIX_MANAGE', false),
  ('RRHH', 'CATALOG_MANAGE', false),
  ('RRHH', 'SYSTEM_CONFIG_VIEW', false),
  ('RRHH', 'SYSTEM_CONFIG_EDIT', false),
  ('RRHH', 'JOB_RUN', false),
  ('RRHH', 'HELP_EDIT', false),
  ('RRHH', 'BILLING_VIEW', false),
  ('RRHH', 'CLIENT_MANAGE', false),
  ('RRHH', 'QUOTE_MANAGE', false),
  ('RRHH', 'INVOICE_MANAGE', false),
  ('RRHH', 'PAYMENT_MANAGE', false),
  ('RRHH', 'LICENSE_MANAGE', false),
  ('CONTADOR', 'DOCUMENT_VIEW', true),
  ('CONTADOR', 'DOCUMENT_DOWNLOAD', true),
  ('CONTADOR', 'DOCUMENT_UPLOAD', true),
  ('CONTADOR', 'DOCUMENT_EDIT', true),
  ('CONTADOR', 'DOCUMENT_FOLIO', true),
  ('CONTADOR', 'DOCUMENT_APPROVE', true),
  ('CONTADOR', 'DOCUMENT_LOCK', true),
  ('CONTADOR', 'DOCUMENT_TRANSFER', true),
  ('CONTADOR', 'DOCUMENT_VERSION_UPLOAD', true),
  ('CONTADOR', 'DOCUMENT_NOTE_ADD', true),
  ('CONTADOR', 'DOCUMENT_METADATA_EDIT', true),
  ('CONTADOR', 'DOCUMENT_TAG_EDIT', true),
  ('CONTADOR', 'DOCUMENT_RELATION_MANAGE', true),
  ('CONTADOR', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('CONTADOR', 'DOCUMENT_TRASH', true),
  ('CONTADOR', 'EXPEDIENTE_VIEW', true),
  ('CONTADOR', 'EXPEDIENTE_CREATE', true),
  ('CONTADOR', 'EXPEDIENTE_EDIT', true),
  ('CONTADOR', 'EXPEDIENTE_CLOSE', true),
  ('CONTADOR', 'EXPEDIENTE_REOPEN', true),
  ('CONTADOR', 'EXPEDIENTE_DELETE', true),
  ('CONTADOR', 'EXPEDIENTE_EXPORT', true),
  ('CONTADOR', 'CORRESPONDENCE_CREATE', true),
  ('CONTADOR', 'TRD_VIEW', true),
  ('CONTADOR', 'TRD_EDIT', true),
  ('CONTADOR', 'TRD_EXPORT', true),
  ('CONTADOR', 'CATEGORY_MANAGE', false),
  ('CONTADOR', 'LOAN_VIEW', true),
  ('CONTADOR', 'LOAN_CREATE', true),
  ('CONTADOR', 'LOAN_RETURN', true),
  ('CONTADOR', 'TRASH_VIEW', true),
  ('CONTADOR', 'TRASH_RESTORE', true),
  ('CONTADOR', 'TRASH_PURGE', false),
  ('CONTADOR', 'DELETION_REQUEST_CREATE', true),
  ('CONTADOR', 'DELETION_REQUEST_REVIEW', false),
  ('CONTADOR', 'PEOPLE_VIEW', true),
  ('CONTADOR', 'PEOPLE_MANAGE', true),
  ('CONTADOR', 'PERSON_EVENT_ADD', true),
  ('CONTADOR', 'ACADEMIC_PERIOD_MANAGE', false),
  ('CONTADOR', 'SEARCH_FULLTEXT', true),
  ('CONTADOR', 'SEARCH_ADVANCED', true),
  ('CONTADOR', 'SEARCH_SEMANTIC', true),
  ('CONTADOR', 'SEARCH_GLOBAL', true),
  ('CONTADOR', 'AI_ANALYZE', true),
  ('CONTADOR', 'AI_CHAT', true),
  ('CONTADOR', 'AI_CLASSIFY', true),
  ('CONTADOR', 'AI_EXTRACT_METADATA', true),
  ('CONTADOR', 'AI_OCR', true),
  ('CONTADOR', 'AI_REPROCESS', false),
  ('CONTADOR', 'AI_USAGE_VIEW', false),
  ('CONTADOR', 'STATS_VIEW', true),
  ('CONTADOR', 'STATS_MODULE_VIEW', true),
  ('CONTADOR', 'AUDIT_VIEW', false),
  ('CONTADOR', 'AUDIT_EXPORT', false),
  ('CONTADOR', 'CUSTODY_VIEW', false),
  ('CONTADOR', 'USER_VIEW', false),
  ('CONTADOR', 'USER_MANAGE', false),
  ('CONTADOR', 'USER_RESET_PASSWORD', false),
  ('CONTADOR', 'USER_SESSION_REVOKE', false),
  ('CONTADOR', 'ROLE_MANAGE', false),
  ('CONTADOR', 'ACCESS_MATRIX_MANAGE', false),
  ('CONTADOR', 'FEATURE_MATRIX_MANAGE', false),
  ('CONTADOR', 'CATALOG_MANAGE', false),
  ('CONTADOR', 'SYSTEM_CONFIG_VIEW', false),
  ('CONTADOR', 'SYSTEM_CONFIG_EDIT', false),
  ('CONTADOR', 'JOB_RUN', false),
  ('CONTADOR', 'HELP_EDIT', false),
  ('CONTADOR', 'BILLING_VIEW', false),
  ('CONTADOR', 'CLIENT_MANAGE', false),
  ('CONTADOR', 'QUOTE_MANAGE', false),
  ('CONTADOR', 'INVOICE_MANAGE', false),
  ('CONTADOR', 'PAYMENT_MANAGE', false),
  ('CONTADOR', 'LICENSE_MANAGE', false),
  ('SIN_ASIGNAR', 'DOCUMENT_VIEW', false),
  ('SIN_ASIGNAR', 'DOCUMENT_DOWNLOAD', false),
  ('SIN_ASIGNAR', 'DOCUMENT_UPLOAD', false),
  ('SIN_ASIGNAR', 'DOCUMENT_EDIT', false),
  ('SIN_ASIGNAR', 'DOCUMENT_FOLIO', false),
  ('SIN_ASIGNAR', 'DOCUMENT_APPROVE', false),
  ('SIN_ASIGNAR', 'DOCUMENT_LOCK', false),
  ('SIN_ASIGNAR', 'DOCUMENT_TRANSFER', false),
  ('SIN_ASIGNAR', 'DOCUMENT_VERSION_UPLOAD', false),
  ('SIN_ASIGNAR', 'DOCUMENT_NOTE_ADD', false),
  ('SIN_ASIGNAR', 'DOCUMENT_METADATA_EDIT', false),
  ('SIN_ASIGNAR', 'DOCUMENT_TAG_EDIT', false),
  ('SIN_ASIGNAR', 'DOCUMENT_RELATION_MANAGE', false),
  ('SIN_ASIGNAR', 'DOCUMENT_PERMISSION_MANAGE', false),
  ('SIN_ASIGNAR', 'DOCUMENT_TRASH', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_VIEW', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_CREATE', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_EDIT', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_CLOSE', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_REOPEN', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_DELETE', false),
  ('SIN_ASIGNAR', 'EXPEDIENTE_EXPORT', false),
  ('SIN_ASIGNAR', 'CORRESPONDENCE_CREATE', false),
  ('SIN_ASIGNAR', 'TRD_VIEW', false),
  ('SIN_ASIGNAR', 'TRD_EDIT', false),
  ('SIN_ASIGNAR', 'TRD_EXPORT', false),
  ('SIN_ASIGNAR', 'CATEGORY_MANAGE', false),
  ('SIN_ASIGNAR', 'LOAN_VIEW', false),
  ('SIN_ASIGNAR', 'LOAN_CREATE', false),
  ('SIN_ASIGNAR', 'LOAN_RETURN', false),
  ('SIN_ASIGNAR', 'TRASH_VIEW', false),
  ('SIN_ASIGNAR', 'TRASH_RESTORE', false),
  ('SIN_ASIGNAR', 'TRASH_PURGE', false),
  ('SIN_ASIGNAR', 'DELETION_REQUEST_CREATE', false),
  ('SIN_ASIGNAR', 'DELETION_REQUEST_REVIEW', false),
  ('SIN_ASIGNAR', 'PEOPLE_VIEW', false),
  ('SIN_ASIGNAR', 'PEOPLE_MANAGE', false),
  ('SIN_ASIGNAR', 'PERSON_EVENT_ADD', false),
  ('SIN_ASIGNAR', 'ACADEMIC_PERIOD_MANAGE', false),
  ('SIN_ASIGNAR', 'SEARCH_FULLTEXT', false),
  ('SIN_ASIGNAR', 'SEARCH_ADVANCED', false),
  ('SIN_ASIGNAR', 'SEARCH_SEMANTIC', false),
  ('SIN_ASIGNAR', 'SEARCH_GLOBAL', false),
  ('SIN_ASIGNAR', 'AI_ANALYZE', false),
  ('SIN_ASIGNAR', 'AI_CHAT', false),
  ('SIN_ASIGNAR', 'AI_CLASSIFY', false),
  ('SIN_ASIGNAR', 'AI_EXTRACT_METADATA', false),
  ('SIN_ASIGNAR', 'AI_OCR', false),
  ('SIN_ASIGNAR', 'AI_REPROCESS', false),
  ('SIN_ASIGNAR', 'AI_USAGE_VIEW', false),
  ('SIN_ASIGNAR', 'STATS_VIEW', false),
  ('SIN_ASIGNAR', 'STATS_MODULE_VIEW', false),
  ('SIN_ASIGNAR', 'AUDIT_VIEW', false),
  ('SIN_ASIGNAR', 'AUDIT_EXPORT', false),
  ('SIN_ASIGNAR', 'CUSTODY_VIEW', false),
  ('SIN_ASIGNAR', 'USER_VIEW', false),
  ('SIN_ASIGNAR', 'USER_MANAGE', false),
  ('SIN_ASIGNAR', 'USER_RESET_PASSWORD', false),
  ('SIN_ASIGNAR', 'USER_SESSION_REVOKE', false),
  ('SIN_ASIGNAR', 'ROLE_MANAGE', false),
  ('SIN_ASIGNAR', 'ACCESS_MATRIX_MANAGE', false),
  ('SIN_ASIGNAR', 'FEATURE_MATRIX_MANAGE', false),
  ('SIN_ASIGNAR', 'CATALOG_MANAGE', false),
  ('SIN_ASIGNAR', 'SYSTEM_CONFIG_VIEW', false),
  ('SIN_ASIGNAR', 'SYSTEM_CONFIG_EDIT', false),
  ('SIN_ASIGNAR', 'JOB_RUN', false),
  ('SIN_ASIGNAR', 'HELP_EDIT', false),
  ('SIN_ASIGNAR', 'BILLING_VIEW', false),
  ('SIN_ASIGNAR', 'CLIENT_MANAGE', false),
  ('SIN_ASIGNAR', 'QUOTE_MANAGE', false),
  ('SIN_ASIGNAR', 'INVOICE_MANAGE', false),
  ('SIN_ASIGNAR', 'PAYMENT_MANAGE', false),
  ('SIN_ASIGNAR', 'LICENSE_MANAGE', false)
ON CONFLICT (role_code, feature_code) DO UPDATE SET enabled = EXCLUDED.enabled;

-- Matriz efectiva: se aplica el valor por defecto solo a las celdas que nadie
-- ha modificado desde el panel.
INSERT INTO role_features (role_code, feature_code, enabled)
SELECT d.role_code, d.feature_code, d.enabled FROM role_feature_defaults d
ON CONFLICT (role_code, feature_code) DO UPDATE
   SET enabled = EXCLUDED.enabled, updated_at = now()
 WHERE role_features.updated_by IS NULL AND role_features.enabled <> EXCLUDED.enabled;
